import { getSession, useSession } from "next-auth/react";
import Head from "next/head";
import Header from "../../components/Header";

function Movie({ result }) {
  //   console.log(result);
  const {session} = useSession();
  return (
    <div>
      <Head>
        <title>{result.title || result.original_name}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
    </div>
  );
}

export default Movie;

export async function getServerSideProps(context) {
  const session = await getSession(context);
  const id = context.query.id;
  const request = await fetch(
    `https://api.themoviedb.org/3/movie/${id}?api_key=${process.env.API_KEY}&language=dk&append_to_response=videos`
  ).then((response) => response.json());

  return {
    props: {
      session,
      result: request,
    },
  };
}
